services:
  - type: web
    name: trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your_secret_key
      - key: DATABASE_URL
        value: sqlite:///trading_bot.db
